name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-build_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: silte/actions/prepare-node-job@v1

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: silte/actions/prepare-node-job@v1

      - name: Eslint
        run: npm run lint

  lint-type:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: silte/actions/prepare-node-job@v1

      - name: Lint TS types
        run: npm run check-types

  # test-frontend:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - uses: silte/actions/prepare-node-job@v1

  #     - uses: silte/actions/test-jest@v1
  #       with:
  #         PACKAGE_ROOT: "frontend"

  # test-backend:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - uses: silte/actions/prepare-node-job@v1

  #     - uses: silte/actions/test-jest@v1
  #       with:
  #         PACKAGE_ROOT: "backend"
